from __future__ import annotations

from job_parser.models import SourceDefinition


def build_sources() -> list[SourceDefinition]:
    return [
        SourceDefinition(
            key="dou_remote_deftech",
            name="deftech.dou remote",
            category="remote, deftech",
            url="https://deftech.dou.ua/jobs/?remote",
            card_selector=".l-items .l-vacancy",
            title_selector="a",
            link_selector="a",
            company_selector="strong",
            date_selector=".date",
            next_selector=".more-btn > a",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="dou_vinnytsia_deftech",
            name="deftech.dou vinnytsia",
            category="vinnytsia, deftech",
            url="https://deftech.dou.ua/jobs/?city=%D0%92%D1%96%D0%BD%D0%BD%D0%B8%D1%86%D1%8F",
            card_selector=".l-items .l-vacancy",
            title_selector="a",
            link_selector="a",
            company_selector="strong",
            date_selector=".date",
            next_selector=".more-btn > a",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="dou_remote_it",
            name="jobs.dou remote",
            category="remote, it",
            url="https://jobs.dou.ua/vacancies/?remote",
            card_selector=".l-items .l-vacancy",
            title_selector="a",
            link_selector="a",
            company_selector="strong",
            date_selector=".date",
            next_selector=".more-btn > a",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="dou_vinnytsia_it",
            name="jobs.dou vinnytsia",
            category="vinnytsia, it",
            url="https://jobs.dou.ua/vacancies/?city=Vinnytsia",
            card_selector=".l-items .l-vacancy",
            title_selector="a",
            link_selector="a",
            company_selector="strong",
            date_selector=".date",
            next_selector=".more-btn > a",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="djinni_remote_it",
            name="djinni remote",
            category="remote, it",
            url="https://djinni.co/jobs/?search_type=basic-search&employment=remote",
            card_selector=".list-jobs > div",
            title_selector=".job-item__position",
            link_selector="a[href]",
            company_selector=".job-item__position + div > span",
            date_selector="[data-original-title]",
            next_selector=".pagination > li:last-child > a",
            date_attribute="data-original-title",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="djinni_vinnytsia_it",
            name="djinni vinnytsia",
            category="vinnytsia, it",
            url="https://djinni.co/jobs/?search_type=basic-search&region=UKR&location=vinnytsia",
            card_selector=".list-jobs > div",
            title_selector=".job-item__position",
            link_selector="a[href]",
            company_selector=".job-item__position + div > span",
            date_selector="[data-original-title]",
            next_selector=".pagination > li:last-child > a",
            date_attribute="data-original-title",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="djinni_remote_deftech",
            name="djinni remote miltech",
            category="remote, deftech",
            url="https://djinni.co/jobs/?search_type=basic-search&employment=remote&editorial=miltech",
            card_selector=".list-jobs > div",
            title_selector=".job-item__position",
            link_selector="a[href]",
            company_selector=".job-item__position + div > span",
            date_selector="[data-original-title]",
            next_selector=".pagination > li:last-child > a",
            date_attribute="data-original-title",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="djinni_vinnytsia_deftech",
            name="djinni vinnytsia miltech",
            category="vinnytsia, deftech",
            url="https://djinni.co/jobs/?search_type=basic-search&region=UKR&location=vinnytsia&editorial=miltech",
            card_selector=".list-jobs > div",
            title_selector=".job-item__position",
            link_selector="a[href]",
            company_selector=".job-item__position + div > span",
            date_selector="[data-original-title]",
            next_selector=".pagination > li:last-child > a",
            date_attribute="data-original-title",
            prefer_playwright=True,
        ),
        SourceDefinition(
            key="work_remote_it",
            name="work.ua remote it",
            category="remote, it",
            url="https://www.work.ua/jobs-remote-it-industry-it/?days=123",
            card_selector="#pjax-jobs-list > div",
            title_selector="h2 > a",
            link_selector="h2 > a",
            company_selector="img",
            date_selector="h2 > a",
            next_selector=".pagination > li:last-child > a",
            company_attribute="alt",
            date_attribute="title",
            prefer_playwright=False,
            wait_for_selector="#pjax-jobs-list h2 > a",
        ),
        SourceDefinition(
            key="work_vinnytsia_it",
            name="work.ua vinnytsia it",
            category="vinnytsia, it",
            url="https://www.work.ua/jobs-vinnytsya-it-industry-it/?days=123",
            card_selector="#pjax-jobs-list > div",
            title_selector="h2 > a",
            link_selector="h2 > a",
            company_selector="img",
            date_selector="h2 > a",
            next_selector=".pagination > li:last-child > a",
            company_attribute="alt",
            date_attribute="title",
            prefer_playwright=False,
            wait_for_selector="#pjax-jobs-list h2 > a",
        ),
        SourceDefinition(
            key="work_remote_deftech",
            name="work.ua remote deftech",
            category="remote, deftech",
            url="https://www.work.ua/jobs-remote-industry-defense-industrial-complex/?days=123",
            card_selector="#pjax-jobs-list > div",
            title_selector="h2 > a",
            link_selector="h2 > a",
            company_selector="img",
            date_selector="h2 > a",
            next_selector=".pagination > li:last-child > a",
            company_attribute="alt",
            date_attribute="title",
            prefer_playwright=False,
            wait_for_selector="#pjax-jobs-list h2 > a",
        ),
        SourceDefinition(
            key="work_vinnytsia_deftech",
            name="work.ua vinnytsia deftech",
            category="vinnytsia, deftech",
            url="https://www.work.ua/jobs-vinnytsya-industry-defense-industrial-complex/?days=123",
            card_selector="#pjax-jobs-list > div",
            title_selector="h2 > a",
            link_selector="h2 > a",
            company_selector="img",
            date_selector="h2 > a",
            next_selector=".pagination > li:last-child > a",
            company_attribute="alt",
            date_attribute="title",
            prefer_playwright=False,
            wait_for_selector="#pjax-jobs-list h2 > a",
        ),
        SourceDefinition(
            key="robota_remote_it",
            name="robota.ua remote it",
            category="remote, it",
            url="https://robota.ua/zapros/ukraine/params;scheduleIds=3;rubrics=1",
            card_selector="alliance-jobseeker-desktop-vacancies-list a.card",
            title_selector="img",
            title_attribute="alt",
            link_selector=None,
            company_selector=None,
            date_selector=None,
            next_selector="santa-pagination-with-links a:last-of-type",
            prefer_playwright=True,
            wait_for_selector="alliance-jobseeker-desktop-vacancies-list a.card",
        ),
        SourceDefinition(
            key="robota_remote_non_ukraine_it",
            name="robota.ua remote non-ukraine it",
            category="remote, it",
            url="https://robota.ua/zapros/other_countries/params;scheduleIds=3;rubrics=1",
            card_selector="alliance-jobseeker-desktop-vacancies-list a.card",
            title_selector="img",
            title_attribute="alt",
            link_selector=None,
            company_selector=None,
            date_selector=None,
            next_selector="santa-pagination-with-links a:last-of-type",
            prefer_playwright=True,
            wait_for_selector="alliance-jobseeker-desktop-vacancies-list a.card",
        ),
        SourceDefinition(
            key="robota_vinnytsia_it",
            name="robota.ua vinnytsia it",
            category="vinnytsia, it",
            url="https://robota.ua/zapros/vinnytsia/params;rubrics=1",
            card_selector="alliance-jobseeker-desktop-vacancies-list a.card",
            title_selector="img",
            title_attribute="alt",
            link_selector=None,
            company_selector=None,
            date_selector=None,
            next_selector="santa-pagination-with-links a:last-of-type",
            prefer_playwright=True,
            wait_for_selector="alliance-jobseeker-desktop-vacancies-list a.card",
        ),
        SourceDefinition(
            key="robota_remote_deftech",
            name="robota.ua remote deftech",
            category="remote, deftech",
            url="https://robota.ua/zapros/ukraine/params;scheduleIds=3;rubrics=1;branchIds=oboronna-promyslovist",
            card_selector="alliance-jobseeker-desktop-vacancies-list a.card",
            title_selector="img",
            title_attribute="alt",
            link_selector=None,
            company_selector=None,
            date_selector=None,
            next_selector="santa-pagination-with-links a:last-of-type",
            prefer_playwright=True,
            wait_for_selector="alliance-jobseeker-desktop-vacancies-list a.card",
        ),
        SourceDefinition(
            key="robota_vinnytsia_deftech",
            name="robota.ua vinnytsia deftech",
            category="vinnytsia, deftech",
            url="https://robota.ua/zapros/vinnytsia/params;branchIds=oboronna-promyslovist",
            card_selector="alliance-jobseeker-desktop-vacancies-list a.card",
            title_selector="img",
            title_attribute="alt",
            link_selector=None,
            company_selector=None,
            date_selector=None,
            next_selector="santa-pagination-with-links a:last-of-type",
            prefer_playwright=True,
            wait_for_selector="alliance-jobseeker-desktop-vacancies-list a.card",
        ),
    ]

